export const FETCH_PRODUCTS = '@FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCES = '@FETCH_PRODUCTS_SUCCES';
export const FETCH_PRODUCTS_FAILURE = '@FETCH_PRODUCTS_FAILURE';

export const ADD_PRODUCTS_CART = '@ADD_PRODUCTS_CART';
